config/routes.rb
Rails.application.routes.draw do


	devise_for :users, :controllers => { registrations: 'registrations' }
	# resources :users
  resources :deeds, only: [:show, :index]
  resources :contributions

  root 'deeds#index'

  post 'twilio/voice' => 'twilio#voice'

  post 'notifications/notify' => 'notifications#notify'

end

app/models/contribution.rb
class Contribution < ActiveRecord::Base

	delegate :content, to: :contribution, allow_nil: true, prefix: true

end

app/models/deed.rb
class Deed < ActiveRecord::Base
end

app/models/twilio_client.rb
# @client = TwilioClient.new
# @client.notify

class TwilioClient
	require 'twilio-ruby'

	def initialize
		@client = Twilio::REST::Client.new ENV["TWILIO_ACCOUNT_SID"], ENV["TWILIO_AUTH_TOKEN"]
	end

	def notify
		all_phone_numbers.each do |number|
			@client.account.messages.create(
				from: '+14012294812',
				to: number,
				body: daily_text
			)
		end
	end

	private

	def daily_text
		@message = [ 
			"Hi there! Thanks so much for subscribing to Selfless. Things have gotten a bit busy, so unfortunately for now, I'll need to pause the daily messages. In the meantime, feel free to visit the forum or edit your account. Again, thanks for working to make the world a more selfless place!"
		].first

		# @message[@index]
	end

	def all_phone_numbers
		User.pluck(:phone_number)
	end

	# def count(index)
	# 	index += 1
	# 	if index >= @message.length
	# 		index = 0
	# 	end
	# end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :phone_number
  end
end

app/controllers/contributions_controller.rb
class ContributionsController < ApplicationController

	before_action :authenticate_user!, except: [:show, :index]


	def index
		@contributions = Contribution.all
		@contribution = Contribution.new

	end

	def show
		@contribution = Contribution.find(params[:id])
	end

	def new
		@contribution=Contribution.new(contribution_params)
	end

	def create
		@contribution = Contribution.create(contribution_params)

		if @contribution.save
			redirect_to :back, notice: "Student was successfully created."
		else
			render :new
		end
	end

	def update
		@contribution = Contribution.find(params[:id])

	end

	def edit
		@contribution = Contribution.find(params[:id])

	end

	def destroy
		@contribution = Contribution.find(params[:id])
		@contribution.destroy
		redirect_to :back
	end

	private

	def contribution_params
		params.require(:contribution).permit(:content,:id)
	end
end

app/controllers/deeds_controller.rb
class DeedsController < ApplicationController

	def index
	end

	def show
	end

end

app/controllers/notification_controller.rb
class NotificationController < ApplicationController
	require 'twilio-ruby'

	skip_before_action :verify_authenticity_token
	before_action :set_twilio_client

	def notify
		@client.messages.create(
			from: '+14012294812',
			to: '+14016515884',
			body: 'Hey there!'
			)
	end

	private

	def set_twilio_client
		twilio_account_sid = ENV["TWILIO_ACCOUNT_SID"]
		twilio_auth_token = ENV["TWILIO_AUTH_TOKEN"]
		@client = Twilio::REST::Client.new twilio_account_sid, twilio_auth_token
	end

end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
	skip_before_action :verify_authenticity_token

	def notify
		client = TwilioClient.new
		result = client.notify
		render plain: result.status
	end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
 
  private
 
  def sign_up_params
    params.require(:user).permit(:phone_number, :email, :password, :password_confirmation)
  end
 
  def account_update_params
    params.require(:user).permit(:phone_number, :email, :password, :password_confirmation, :current_password)
  end
end

app/controllers/twilio_controller.rb
require 'twilio-ruby'
 
class TwilioController < ApplicationController
  include Webhookable
 
  after_filter :set_header
 
  skip_before_action :verify_authenticity_token
 
  def voice
    response = Twilio::TwiML::Response.new do |r|
      # Do these uppercase method names work?
      r.Say 'Welcome to Selfless! Check out selfless-app.com for more information or account editing.', voice: 'alice'
      r.Play 'http://linode.rabasa.com/cantina.mp3'
    end
 
    render_twiml response
  end
end

app/controllers/webhookable.rb
module Webhookable
	extend ActiveSupport::Concern
	
	def set_header
		response.headers["Content-Type"] = "text/xml"
	end
	
	def render_twiml(response)
		render text: response.text
	end
	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/contributions/_form.html.erb
<%= form_for(@contribution) do |f| %>
  <div class="field">
    <%= f.label :submit_your_own_idea %>:<br>
    <%= f.text_field :content %>
  </div>
  <br>
  <div class="actions" >
    <%= f.submit "Submit Anonymously", class: 'btn btn-success btn-sm' %>
  </div>
  <br>
<% end %>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <h5><a href="https://github.com/laurenfazah/SelflessApp" target="_blank">Selfless created by Lauren Fazah, 2014</a></h5>
</div>

app/views/contributions/index.html.erb
<br>
<br>
<br>
<br>
<div class = "container">
	<div class = "row">
		<div class = "col-xs-12">
			<h1>Good Deeds Forum</h1>
		</div>
	</div>
	<div class = "row">
		<div class = "col-xs-8">
			<% @contributions.each do |contribution| %>
				<%= contribution.content %>  <%= link_to 'Delete', contribution, method: :delete, data: { confirm: 'Are you sure?' } %><br>
			<% end %>
		</div>
		<div class = "col-xs-4">
			<%= render 'form' %>
		</div>	
	</div>
</div>
<br>

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-56162004-1', 'auto');
  ga('send', 'pageview');

</script>

app/views/deeds/index.html.erb
<div id="myCarousel" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
    <li data-target="#myCarousel" data-slide-to="1"></li>
  </ol>
  <div class="carousel-inner">
    <div class="item active">
      <%= image_tag "holi.jpg" %>
      <div class="container">
        <div class="carousel-caption">
          <h1>Welcome to Selfless!</h1>
          <h3>Selfless is sending you daily reminders of good deeds you can make happen <strong>straight to your phone.</strong></h3>    
          <p>
            <% if user_signed_in? %>
              <%= link_to 'Edit Account', edit_user_registration_path, class: "btn btn-lg btn-primary caro" %></li>
            <% else %>
              <%= link_to 'Sign Up', new_user_registration_path, class: "btn btn-lg btn-primary caro" %></li>
            <% end %>
          </p>
        </div>
      </div>
    </div>
    <div class="item">
      <%= image_tag "color_wood.jpg" %>
      <div class="container">
        <div class="carousel-caption">
          <h1>Did you know...</h1>
          <h3>that performing acts of kindness are extremely beneficial for both you and the people you affect?<br><br>
          Visit our Good Deeds Forum to see the good others have done and perhaps share your own ideas!</h3>
          <br>
          <p><a class="btn btn-lg btn-primary caro" href="/contributions" role="button">Good Deeds Forum</a></p>
        </div>
      </div>
    </div>
  </div>
  <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev"><span class="glyphicon glyphicon-chevron-left"></span></a>
  <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next"><span class="glyphicon glyphicon-chevron-right"></span></a>
</div>

<div class = "container">
  <div class = "row">
    <div class = "col-xs-12">
      <h2>How Selfless Works:</h2>
    </div>
  </div>
  <div class = "row">
    <div class = "col-xs-12">
      <h4>Selfless is a web application designed to send its users reminders of good deeds they can do each day. By signing up, you are allowing Selfless to send text messages to the phone number that you provide. If you no longer wish to subscribe to these text messages, simply delete your account from the "Edit Account" page.</h4>
      <h4>By becoming a member of Selfless, you are also given access to our Good Deeds Forum. Users can contribute their own ideas for good deeds, read other users' ideas, and are also given the power to delete others' contributions if deemed inappropriate.</h4>
      <h4>I hope you enjoy Selfless! If you have any further questions, feel free to email me at laurenfazah@gmail.com</h4>
    </div>
  </div>
</div>

<div class = "container">
  <div class = "row">
    <div class = "col-xs-12">
      <h2>Learn More:</h2>
    </div>
  </div>
  <div class = "row">
    <div class = "col-xs-12">
      <h4><a href="http://www.psychologicalscience.org/index.php/news/releases/investing-in-karma-by-doing-good-deeds.html" target="_blank">Investing in Karma by Doing Good Deeds, Association for Psychological Science</a></h4>
      <p><i>The researchers believe that investing in karma may be a positive way for us to cope with the otherwise unpleasant experience of just sitting around and waiting. “Even if people don’t actually believe in karma, they may still have an intuitive sense that good things happen to good people. If that intuition moves us to donate to a good cause and makes us a little more optimistic in the meantime, that seems like a good thing,” they conclude.</i></p><br>
      <h4><a href="http://www.huffingtonpost.co.uk/sandi-mann/paying-it-forward-random-good-deeds_b_2629556.html" target="_blank">Paying It Forward: The Psychology of Random Good Deeds, HuffPost UK</a></h4>
      <p><i>According to a study by Stanford University psychologist Sonja Lyubomirsky in 2005, students who carried out five random acts of kindness a week, reported higher levels of happiness than a control group. That I can understand; we feel good when we do good because we feel that we have made a positive contribution to society and we experience what psychologist call 'moral elevation'.</i></p><br>
      <h4><a href="http://greatergood.berkeley.edu/article/item/kindness_makes_you_happy_and_happiness_makes_you_kind" target="_blank">Kindness Makes You Happy… and Happiness Makes You Kind, Berkeley.edu</a></h4>
      <p><i>Two recent studies suggest that giving to others makes us happy, even happier than spending on ourselves. What’s more, our kindness might create a virtuous cycle that promotes lasting happiness and altruism.</i></p><br>
      <h4><a href="http://greatergood.berkeley.edu/article/item/how_good_news_can_inspire_good_deeds" target="_blank">How Good News Can Inspire Good Deeds, Berkeley.edu</a></h4>
      <p><i>“We have reason to believe that even a seemingly weak stimulus, like a story of moral goodness, can evoke moral elevation responses in nonexperimental settings,” write the authors. Therefore, if the news were to report on impressive good deeds more frequently, perhaps we would see a far-reaching ripple effect among readers.</i></p><br>
      <h4><a href="http://www.webmd.com/balance/features/science-good-deeds" target="_blank">The Science of Good Deeds, WebMD</a></h4>
      <p><i>Only in recent years have researchers explored the scientific underpinnings of the notion that "doing good" is indeed a good thing -- and precisely why it is good for us. Indeed, many scientific disciplines -- evolution, genetics, human development, neurology, social science, and positive psychology -- are at the heart of this investigation, says Post.</i></p><br>
      <br>
      <br>
      <span id="credit">
        <h5><a href="https://github.com/laurenfazah/SelflessApp" target="_blank">Selfless created by Lauren Fazah, 2014</a></h5>
        <p><a href="https://flic.kr/p/bsVPYG" target="_blank">Holi photo by Irwin Scott</a></p>
        <p><a href="https://flic.kr/p/omo9Fc" target="_blank">Wood photo by Judi May</a></p>
      </span>
    </div>
  </div>
</div>

app/views/layouts/_nav.html.erb
<div class="navbar-wrapper">
  <div class="container">

    <div class="navbar navbar-inverse navbar-static-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/deeds">Selfless</a>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to 'Good Deeds Forum', contributions_path %></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Account<span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <% if user_signed_in? %>
                  <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
                <% else %>
                  <li><%= link_to 'Login', new_user_session_path %></li>
                <% end %>
                <% if user_signed_in? %>
                  <li><%= link_to 'Edit Account', edit_user_registration_path %></li>
                <% else %>
                  <li><%= link_to 'Sign Up', new_user_registration_path %></li>
                <% end %>
              </ul>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SelflessApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/nav' %>

<%= yield %>

</body>
</html>